### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#109]
AltSnap seems unnecessarily sluggish to first time users and such, which don't look into .ini files, due to the standard values of `RefreshRate` `MoveRate` and `ResizeRate`.
I lowered the values to `RefreshRate=0` `MoveRate=1` and `ResizeRate=2` and couldn't find any situation in which these values would perform worse than higher rates. 
Only `ResizeRate=1` felt in rare instances more juddery than` ResizeRate=2`

**Comment by RamonUnch** [comment]
It is planned to change those default values for AltSanp.
The other default values are here because they were mitigating bugs that had not been fixed under the older versions of AltDrag. But for the most part, now the values you suggest are better, especially under Win10 which has very wired behaviors.

**Comment by RamonUnch** [comment]
Done for AltSnap 1.47
