### ISSUE TITLE
Choco package for AltSnap in moderation

### ISSUE THREAD

**Issue by mebo** [RamonUnch/AltSnap#114]
I noticed that the [choco package](https://community.chocolatey.org/packages/altsnap) for AltSnap is in moderation due to what looks like a false positive from a virus scanner (due to known reasons).

The false positives from scanners are a pita I can imagine, do you have an estimate when this can be resolved?

**Comment by RamonUnch** [comment]
Indeed it is a pity, but not a big deal, as long as it stays under 5 positive under virustotal, it seems OK for chocolatey.
AltDrag was a 'trusted package' after a few releases, AltSnap is not yet, so it will take a few days before it is accepted, because of manual review (which is all fine for me).

For  SecureAge APEX , I submitted a false positive issue and the file should be whitelisted in a 48-72h.
Same for Rising antivirus. so now it seems everything is clean, but chocolatey never re-scans under virustotal, so it always stays there I do not know if this can be solved, other than by waiting for antiviruses false positive correction before submission to choco.

**Comment by RamonUnch** [comment]
https://www.virustotal.com/gui/file/a3b0d8b63e42f965632fed8c1074afb740a20439474be3905435e33b1167a15a
https://www.virustotal.com/gui/file/405c290d2cf49f2a85a62e6368c6e2eef8eed7cb9bd4201c11b7b3801cb8d1e0

**Comment by mebo** [comment]
Ah I didn't know that the wait is for manual review, that explains a lot and only asks from some patience :)

Thanks!

(btw pita = pain in the behind :) )
