### ISSUE TITLE
Please allow alt-click in windows

### ISSUE THREAD

**Issue by bogdanb** [RamonUnch/AltSnap#126]
Hi! I pretty much can’t use Windows without this app. Thank you for it!

But there is a tiny problem: when AltSnap is enabled, I can no longer use any Alt+Click commands in applications. Unfortunately there are such commands that I cannot reassign to other combinations.

It would be great to be able to still use those. I imagine AltSnap captures all mouse events when Alt is held down. It should be possible to let them pass through when the mouse does not move during the click (with maybe a few pixels of slack). Or, since you can’t know on mouse-down if the button will be released before moving, there could be an option to send a “synthetic” set of events for a click, right after the raising the button, as long as the mouse moved less than X (or not at all) during the click.

**Comment by RamonUnch** [comment]
Handling alt+click without drag is indeed in my todo list, However, the way messages loops work make it complex to implement, and I cannot yet find a solution to have it working with all applications, because sending key messages is not universally working (especially on Windows 8/10). In the current state you can:
* Use the WinKey instead of Alt (Fixes 95% of the problems),
* Use a key combo (alt+win) and you will almost never have conflicts (99.9%).
* If you have a program that you do not move much with AltSnap and in which you want to use Alt+click, you can blacklist it.
* If you occasionally need to have alt+click not blocked by AltSnap, then you can press Alt, then hit ctrl, whule keeping alt down, then click and AltSnap will not interact.

**Comment by bogdanb** [comment]
Thank you very much, I did not know the trick with tapping Ctrl while Alt is held down. At least for my use case that completely solves the problem!

**Comment by woctezuma** [comment]
> when AltSnap is enabled, I can no longer use any Alt+Click commands in applications

It looks like my issue with VS Code!
- https://github.com/microsoft/vscode/issues/141238
- https://github.com/RamonUnch/AltSnap/issues/153

**Comment by woctezuma** [comment]
Great fix with Ctrl indeed!

**Comment by RamonUnch** [comment]
Actually Alt+click is disabled in "all" programs, so if you have AltSnap enabled and you are using Alt as a hotkey, it will disable Alt+click in all applications. I am working on a fix, but I am not on what to do yet because AltSnap need to block the click because you do not want to click on applications when moving them.

**Comment by Ichisich** [comment]
It's the same with CTRL+click.
To be honest, I never got why Stefan Sundin chose ALT as the default and not WIN.
WIN+click isn't really a thing, and thus the ideal macro button.

**Comment by RamonUnch** [comment]
> To be honest, I never got why Stefan Sundin chose ALT as the default and not WIN.
WIN+click isn't really a thing, and thus the ideal macro button.

I think the main reason is because ALT is the the default on most windows managers on Linux (at least when I was actively using it).
When you get used to the Alt key, you do not want to change, especially if you are alternating between random Linux and Windows computers, probably you can easily change the hotkey for Linux too, but defaults for defaults makes sense.
The two reasons I keep Alt as the default hotkey is 1) to mimic original AltDrag's behavior and 2) for people used to Linux.

Finally Alt+Click is getting more and more common but it used to be almost nonexistent, as the windows API was giving a special treatment to Ctrl and Shift instead (when treating windows messages), making it easy and natural to use exclusively Ctrl/Shift+Click instead of Alt or Win+Click.
Personally I almost never use Alt+Click in any programs.

**Comment by Ichisich** [comment]
Thoroughly reasoning.
It's true, and I'm personally not a fan of nudging either.
Making WIN default in AltSnap would initially confuse AltDrag and Linux user for the price of solving some niche incompatibly cases.

> Personally I almost never use Alt+Click in any programs.
As you said, it becomes slowly more common.
Even Windows system software uses it nowadays, e.g. Explorer (properties) or Paint3D (dragging).

Perhaps in 10 years it gets so common nudging becomes warranted.

**Comment by RamonUnch** [comment]
@bogdanb @woctezuma 
Well I actually made a "working" solution:
You can now do Alt+Long click, and the click will "pierce" through AltSnap to the program (IF you do not move the cursor).
You can also set `PiercingClick=1` in the `[Advanced]` section of the .ini file. and Alt+Click will be transmitted unless you move the cursor. If you enable PiercingClick, you will be unable to use doubleclick actions in altdrag (some people probably wont care).

Replace the hooks.dll in your AltSnap folder with the appropriate one (quit AltSnap first):
x64 build of hooks.dll: [hooks_x64.zip](https://github.com/RamonUnch/AltSnap/files/7941203/hooks_x64.zip)
i386 build of hooks.dll: [hooks_i386.zip](https://github.com/RamonUnch/AltSnap/files/7941199/hooks_i386.zip)

ini file option:
```
in the [Advanced] section

PiercingClick=1
; set to 1 to enable, in this case, if you press Alt+Click without moving,
; the click will be transmitted to the pointed program.
; Enabling this option will disable doubleclicking actions!
; if you keep it disabled (default) you still will have the click
; transmission if you hold the click down more than a double click delay.
```

**Comment by woctezuma** [comment]
Wow! Thank you! You are really good at explaining things, and really fast at fixing issues! 🎉

**Comment by woctezuma** [comment]
I have tried both fixes (with the x64 DLL file), and they work perfectly fine!

I prefer the piercing click, so I settle with this fix! Thank you!

**Comment by bogdanb** [comment]
I got so used to the Alt+Ctrl+release_Ctrl combo that I don’t even notice when I use it. The piercing click trick sounds like it would be useful if my use case was a bit different. Or maybe if it just worked without having to do anything I’d still try it.
