### ISSUE TITLE
Option to disable snapping entirely

### ISSUE THREAD

**Issue by shoogstoel** [RamonUnch/AltSnap#127]
Thanks for the great work you've done!

Would it be possible to add an option to disable snapping entirely? I use the shift key as a modifier for something else.

**Comment by RamonUnch** [comment]
for now the border-border snapping is forced by the shift key, however, if you use Shift as a modifier for an alternate action, it should override the old behavior and shift will no longer enable snapping behavior, so I am not sure what your problem is here? you mean you are using shift for an other program?

**Comment by shoogstoel** [comment]
Yes, it is used by another program (FancyZones to be precise). Sorry for not being more precise in the first place.

**Comment by RamonUnch** [comment]
Ok, I think the best would be to have a custom key instead of hardcoding shift for this. I will implement this soon.

**Comment by shoogstoel** [comment]
You are right and I agree with you, a customizable key would be the better way to achieve that. I just didn't want to ask for too much right away 😉

**Comment by RamonUnch** [comment]
[AltSnap1.48test17.zip](https://github.com/RamonUnch/AltSnap/files/7538351/AltSnap1.48test17.zip)
Try with this combo AltSnap+Hooks.dll (for 64 bit Windows), then set in the [Input] section of AltSnap.ini
```
Shiftkeys=
; Key that is used to snap windows
; defaut sis A0 A1 for left and right shift.

```
You can any set of keys to replace the shift key, this applies to all uses of shift, not just snapping.
If you set an empty value then no keys will be assigned for shift and it will no longer interact with AltSnap.

**Comment by shoogstoel** [comment]
Works like a charm, thanks for the quick update! Now if I could get FancyZones to trigger while holding down ALT, that'd be perfect. Different story though :)

**Comment by RamonUnch** [comment]
This is not possible, because it is not deeply integrated into power-toys, but AltSnap simulate its own FancyZones that you can setup with test windows, see the [wiki](https://github.com/RamonUnch/AltSnap/wiki#snap-layout-configuration) for more details. For this you will need to re-enable Shift though. The trick is to configure AltSnap to use the same zones than PowerToys's FancyZones, then you will be able to snap them to the zones using the title-bar (via PowerToys) or with AltSnap while dragging.

**Comment by shoogstoel** [comment]
Yea, I figured as much. Thanks for pointing out the zones option, gonna give it a try.
