### ISSUE TITLE
Very sluggish compared to AltDrag

### ISSUE THREAD

**Issue by Borderliner** [RamonUnch/AltSnap#129]
Was happy to see the old project being maintained now. However this happiness didn't last much as I found out how laggy and sluggish AltSnap is compared to AltDrag. This mostly occurs when resizing, even moving is weird on 144Hz monitor. Please address this issue, thanks. For now I'm back to AltDrag.

**Comment by RamonUnch** [comment]
Did you try to increase the MoveRate/refreshRate values?

```
[Performance]
RefreshRate=0
; Minimum delay, in milliseconds, between two refreshes of a window.
; For minimum CPU usage use a value around your monitor's rate:
; 60Hz monitor => RefreshRate=16
; Max value is 255 (4 Hz), sane values are below 100 (10 Hz).
; If set to 0 (default), you get the most reactivity.

MoveRate=1
ResizeRate=2
; The number of pixels to wait before actually moving the window.
; If set to 1, updates will be instant. You will have better perf with higher values,
; but you will lose precision in moving/resizing. Sane values are below 10.
; Recommended is 1 to 5
```

I think AltDrag default was MoveRate=2 and ResizeRate=5, you can play around with those values, If you are using high refresh-rate monitor I suggest you keep RefreshRate=0, then you can try to increase to see if it improves preformances.
AltSnap went back to a more "smooth" movements because most computers can handle this today, I think I will revert to more conservative defaults for next release.

**Comment by RamonUnch** [comment]
I will also ask that you read the READ FIRST pinned comment https://github.com/RamonUnch/AltSnap/issues/93, where this common issue is listed as no. 3.

**Comment by Borderliner** [comment]
Thanks, works like a charm!
