### ISSUE TITLE
Disable restore window size when using altsnap to move window

### ISSUE THREAD

**Issue by elnoelsi** [RamonUnch/AltSnap#133]
So i often use "maximize vertically" and when moving the window with altsnap the previous size is restored which is a pain in the ass (for me), but when using normal windows  title bar movement the size is kept, anyway to have that behavior with altsnap move?

**Comment by Ichisich** [comment]
`SmartAero` in the AltSnap.ini is what you're looking for.

**Comment by RamonUnch** [comment]
Indeed if Add 4 to your current `SmartAero` value, windows will never be restored to the pre-snapped state.
When you move via the title bar AltSnap does not kick in, so it cannot restore the window, unless you Alt-drag it.
Maybe I should add an option to select which kind of snapping AltSnap should restore so that you get a finer control of what is restored. For exemple I could add that if a window is maximized vertically then it does not get restored but that it still dors restore windows snapped to the sides.
What do you think?

**Comment by elnoelsi** [comment]
A dedicated option for "maximized vertically" would be probably nice for some people, but i think by default manually resized windows should never be restored, so that smart snapped/resized windows get restored and manually resized arent restored regardless where they are snapped to. Probably thats basically what you meant but i dont use the smart aero/snap.

Anyway so far with `SmartAero 4`  im satisfied, just would be nice to have those kind of options in the UI.

Thanks!

**Comment by elnoelsi** [comment]
oh, side note and quite unrelated question, any chance you could implement a feature to resize vertical taskbar width without limits? Windows has quite a chunky vertical taskbar.

I know 7+ Taskbar Tweaker is a thing but im not a big fan because its slightly unreliable and try to keep to a minimum 3rd party windows modifications. Altsnap has been great for most of the things i need (maximaze vertically, snap without borders, super altF4, etc) so it would be great having that tweak also on altsnap.

**Comment by RamonUnch** [comment]
by default the taskbar is blacklisted so AltSnap does not interact with it, try to remove the `|Shell_TrayWnd`entry from the blacklist, and, then you should be able to resize the taskbar. Not sure windows will like it but you can try.

**Comment by RamonUnch** [comment]
The reason I restore snapped-resized windows by default when Smart aero-snapping is enabled is that it is a window behavior on windows 10, However by default a vertically-maximized+resized windows will not be restored by AltSnap.

**Comment by RamonUnch** [comment]
I added the "Never restore AltSnapped windows" option in the Advanced tab of config as well as the "Smarter Aero snapping option". in the General tab.
only AltSnap.exe and language folder needs updating:
[AltSnap.zip](https://github.com/RamonUnch/AltSnap/files/7656468/AltSnap.zip)
New strings:
GeneralSmarterAero=Smarter Aer&o Snap dimensions
AdvancedNoRestore=Never restore AltSna&pped windows

**Comment by RamonUnch** [comment]
PS: above is build for i386, if you have x64 edition, use this one:
[AltSnap_x64.zip](https://github.com/RamonUnch/AltSnap/files/7656475/AltSnap_x64.zip)

**Comment by Ichisich** [comment]
The combination: 
(Never restore AltSnaped Windows = enabled) + (Smarter Aero Snap Dimensons = disabled)
disables smart aero dimensions passively.

**Comment by RamonUnch** [comment]
>The combination:
(Never restore AltSnaped Windows = enabled) + (Smarter Aero Snap Dimensons = disabled)
disables smart aero dimensions passively.

This is expected because, if you enable **Never restore AltSnaped Windows**, then as soon as a window is resized it clears its restore flag and the Smart Aero dimentions consider only windows with the restore flag.
If you enable Smarter snapping, then all window are considered as snapping friends, so this first option does not matter.
After consideration I agree with you though, it would make more sens if resizing would not clear restore flag, even with the Never restore  option.

**Comment by RamonUnch** [comment]
Done:
[hooks_x64.zip](https://github.com/RamonUnch/AltSnap/files/7656731/hooks_x64.zip)
[hooks_i386.zip](https://github.com/RamonUnch/AltSnap/files/7656732/hooks_i386.zip)
It is not perfect yet because the restore flag is cleared on a single Alt+leftclic, but it is not cleared on resizing

**Comment by RamonUnch** [comment]
All fixed in 1.49, I guess, open a new issue if you encounter more problems...
