### ISSUE TITLE
Closing excel with mouse button closes all open windows

### ISSUE THREAD

**Issue by darsor** [RamonUnch/AltSnap#135]
I love this program! Thanks for the continued development.

When closing a Microsoft Excel window with a configured mouse button, all Excel windows are closed (not just the one that is clicked). The expected behavior would be to only close the window that was clicked.

**Comment by RamonUnch** [comment]
Indeed interesting, Excel has a strange way of handling multiple windows...
I will see on how I can fix that.

**Comment by RamonUnch** [comment]
Fixed, it was a stupid error from my side, instead of sending   `WM_SYSCOMMAND+SC_CLOSE`, i was sending `WM_CLOSE` that may be used to quit the proram. most of the time it changes nothing but here it does.
Just Qui AltSnap, delete the old hooks.dll and replace with the appropriate one:
If you are using x64 build of AltSnap: [hooks-1.49test3-x64.zip](https://github.com/RamonUnch/AltSnap/files/7734043/hooks-1.49test3-x64.zip)
If you are using i386 build of AltSnap: [hooks-1.49test3-i386.zip](https://github.com/RamonUnch/AltSnap/files/7734033/hooks-1.49test3-i386.zip)
Tell me if it fixes it for you.

**Comment by darsor** [comment]
Thanks for the quick turnaround. The fix works great!

**Comment by RamonUnch** [comment]
Included in the 1.49 release
