### ISSUE TITLE
AltSnap interferes w/ Windows 10 clipboard history

### ISSUE THREAD

**Issue by jockie** [RamonUnch/AltSnap#144]
Hello RamonUnch,

first things first: Thanks for picking up the AltDrag project and continuing! I stopped using AltDrag a while ago because of some bugs and was very pleased when I saw that you forked it.

Now to one issue I'm having with AltSnap: I'm using the Win10 (Windows 10 Pro, version 21H1, build 19043.1466) clipboard history feature quite heavily. When I have the cursor in text input boxes in some programs while AltSnap enabled, sometimes AltSnap seems to interfere with the small clipboard history window that usually shows up when pressing ⊞+V. The clipboard window flashes up shortly and disappears almost immediately. Disabling AltSnap ends this behaviour.

I've already tried to get a hold of the hWND of that small clipboard history window with the identify tool window that's built into the blacklist tab to no avail. I simply cannot identify the clipboard history tool using the crosshairs and cannot figure out the clipboard history window's process name either.

Would you mind having a try?

Best Regards,
jockie

**Comment by RamonUnch** [comment]
Could you try to add the V key (code 56)to the kill key list in the [input] section of the .ini file:
eg: `Killkeys=09 4C 2E 56`
I guess you are using the WinKey as a hotkey...

I am not sure I understand, unfortunately I cannot test on Win10, because I no longer have a win10 environment...
You got the problem only when opening with `Win+V` ?

**Comment by RamonUnch** [comment]
Also maybe elevating AltSnap may fix it (you can do it from the tray menu), maybe you already do...

**Comment by RamonUnch** [comment]
@Ichisich 
AltSnap sends Ctrl at the end of a movement, to avoid menu activation, a movement should occur to trigger this though.
Maybe then try running AltSnap non-elevated, in this case (if the cb history is elevated), when releasing the WinKey, AltSnap will not be informed of the WinKeyUP event and this may make him beleave the user is still moving the window and hence send ctrl as soon as a click occurs or something.

Also maybe this is due to keyboard repetition, If you press Win+V slow or fast.

Also maybe @jockie used the **Action without click** option?

**Comment by Ichisich** [comment]
> AltSnap sends Ctrl at the end of a movement, to avoid menu activation, a movement should occur to trigger this though. 

Native movement would also cancel the cb history, every mouse input, besides clicking into the box directly, leads to cancellation.


> Also maybe this is due to keyboard repetition, If you press Win+V slow or fast.

Tried it and no, the cb history is always stable. AltSnap even is the only program I can interact with the cb box stably.
If I press win+v and keep win pressed, I can drag and drop the clipboard, a feat usually impossible.


> Also maybe @jockie used the **Action without click** option?

That would be my guess, too.
I wager it's some setting he's using, and looking at his .ini would reveal the culprit.

**Comment by RamonUnch** [comment]
Latest 1.49 release might have fixed it because all keys from A-Z are now by default acting as kill-keys.
This should avoid more interaction with system shortcuts, and should not harm AltSnap features.
@jockie Tell me if it fixes it for you...

**Comment by RamonUnch** [comment]
@jockie 
It has been a month you submitted this issue is it solved?

**Comment by RamonUnch** [comment]
I am closing this one, it was inactive for too long and is not reproducible.
Feel free to re-open if needed.
