### ISSUE TITLE
Alt Dragging always shows windows content, despite Windows (OS) Settings

### ISSUE THREAD

**Issue by bocadoce** [RamonUnch/AltSnap#156]
Personally, I like to disable the option "Show windows content when dragging", on Windows Settings, to avoid some weird artifacts that sometimes can cause glitches or even system/application crashes.

Unfortunately (for me), when I alt drag a window it's content is shown as I drag it, and, because I got too used too fast with this software,  sometimes I even "over drag" the windows just for the satisfaction of doing it (I really love AltSnap) that I end up running into more artifacts than before.

So, I would like to know if it there is a way to tweak the alt drag behavior to act accordingly to Windows Settings

**Comment by Ichisich** [comment]
The is the option `FullWin=0` int the altsnap.ini but it's janky.
Alternatively, you could lower `opacity when moving` the in the advanced tab.

**Comment by bocadoce** [comment]
> There is the option `FullWin=0` in the altsnap.ini, but it's janky. Alternatively, you could lower `opacity when moving` in the advanced tab.

Indeed, `FullWin=0` is unusable, but found the second suggestion interesting,
I will need some time to try it out and see if it is a nice alternative to what I was looking for
By now, first impressions are good!

Thank you very much!!

**Comment by RamonUnch** [comment]
@bocadoce 
I am working on a fixed `FullWin=0` mode, that works with newer windows
Have a try with this version of hooks.dll

You can set the color of the dragged rectangle (default violet):
```
in the [Input] section of the .ini file:
FrameColor=80 00 80
; Hexadecimal Color in R G B of the hollow rectangle that is used when
; you disabled the FullWin option/Show window content while dragging
; eg: 00 00 00 for black, FF 00 00 for red, 80 00 80 dark violet...
```
And if you set FullWin=2, AltSnap will follow the current Windows config.

The hollow rectangle is NOT the same as the system one, I do not know performant ways to make a GDI XOR mask on Windows 8.x/10, because GDI is litterally a few thousands time slower than on Windows 9x/NT/XP/Vista/7.

64 bits version:  [hooks1.50test3_x64.zip](https://github.com/RamonUnch/AltSnap/files/7979624/hooks1.50test3_x64.zip)
32 bits version: [hooks1.50test3_i386.zip](https://github.com/RamonUnch/AltSnap/files/7979625/hooks1.50test3_i386.zip)

**Comment by bocadoce** [comment]
@RamonUnch

For me it's perfect already! Thank you very much
Maybe adding an outline border with a different color would be nice to avoid any confusion with the background, but, for now, the default violet color is good enough for that purpose

I'm really happy with this feature

**Comment by me-2k** [comment]
@RamonUnch thank you very much for this! I tried your hooks.dll and it works great.

Some windows are slow on redrawing the contents when resizing (for example adobe reader auto zooming the pdf and such) so to be able to resize only the border is a lot quicker!
