### ISSUE TITLE
How to update from old to new AltSnap1.xxbin_x64.zip ?

### ISSUE THREAD

**Issue by PhoenixCODE2322** [RamonUnch/AltSnap#176]
I Know there is chocolately and winget packaging but is there a way to update the zip version without loosing the config.
I just started using Alt snap with last couple releases and noticed that when i overwrote the old files with new one all configs were reset.
So i setted it up again but now here is another update, is there any way to update ? 

Or do i have to compare the config of old and new and paste my values from old. is this the way ?

**Comment by RamonUnch** [comment]
Just extract everything and replace the old files **except the .ini file,**
The old .ini file should always work. in case it does not, then try the new .ini file.

Sometime I advise to use the new ini file (if you upgrade from 1.4x to 1.5x for instance) but it is not necessary and the old ini should work jsut fine. the thing is that several old settings make no more sense in the latest release, so if you have to manually edit the ini file you will have a lot of confusion if there is a lot of version differences.

So as a rule of thumb you can keep the old ini, and in case your config has to be modified because of the update and if you need to manually edit the ini file, then I would recommend you use the latest ini and re-configure from here. This should not happen much though.

The installer simply does not override the ini file, same installer for choco/winget/github page.

**Comment by RamonUnch** [comment]
Added to the wiki and mentioned there.
