### ISSUE TITLE
Framecolor not set correctly to RGB value specified

### ISSUE THREAD

**Issue by onguarde** [RamonUnch/AltSnap#225]
![image](https://user-images.githubusercontent.com/681355/180416374-0adbb924-9c29-4caf-9de5-84fcc60be5fa.png)

> FrameColor=65 165 238
> ; Hexadecimal Color in R G B of the hollow rectangle that is used when
> ; you disabled the FullWin option/Show window content while dragging

This is supposed to be blue colour. But from the video below, it seems to be a brown colour, I'm not sure where I went wrong. Is this a bug?

https://user-images.githubusercontent.com/681355/180416781-1a6ad533-bfd8-489f-8a8e-4d16e126ce75.mp4

> FrameColor=FF 00 00 
> ; eg: 00 00 00 for black, FF 00 00 for red, 80 00 80 dark violet...

Setting to red colour per the docs does work though.

**Comment by Ichisich** [comment]
You need the hex code not rgb.
So in your case FrameColor=41 a5 ee

**Comment by onguarde** [comment]
Works perfectly now, thanks. 

The comments section is pretty confusing. It mentions both Hexadecimal and RGB
; **Hexadecimal** Color in **R G B** of the hollow rectangle that is used when
; you disabled the FullWin option/Show window content while dragging
; eg: 00 00 00 for black, FF 00 00 for red, 80 00 80 dark violet...


Anyway if it's Hex, the letters should be written without spaces right?
> FrameColor=41A5EE

**Comment by Ichisich** [comment]
> Anyway if it's Hex, the letters should be written without spaces right?

No, the spaces are required to seperate the R G B codes.

**Comment by RamonUnch** [comment]
I could change the parsing code but I like to use the same than the hotkeys list so each hex value is space separated. This choice is quite arbitrary but it is simpler to code and .ini file edition is an advanced feature so I guess having to respect strict syntax is not a big deal.

**Comment by RamonUnch** [comment]
> ps. I think BLUE should be the default colour, PINK seems a little too over the top.

I somewhat agree but because the default Windows theme is blue, a blue hollow rectangle would be almost invisible in the default setup I tested it. Also the wallpaper is blue by default.
After some testing I opted for a pink rectangle that may look funny to some people but to my eyes it looks more dark magenta than actual pink, not that I am an artist or anything. So if I change the default color it would have to be visible on a clean win10/11 install.

**Comment by onguarde** [comment]
Thanks for explaning the constraints, I'm ok to live with that.

I still think the comments section should be clarified, that's where my confusion started. 
The comments section is pretty confusing. It mentions both Hexadecimal and RGB.
Perhaps just remove any mention of RGB in the comments. 

; Hexadecimal Color in R G B of the hollow rectangle that is used when
; you disabled the FullWin option/Show window content while dragging
; eg: 00 00 00 for black, FF 00 00 for red, 80 00 80 dark violet...

**Comment by RamonUnch** [comment]
>I still think the comments section should be clarified, that's where my confusion started.
The comments section is pretty confusing. It mentions both Hexadecimal and RGB.
Perhaps just remove any mention of RGB in the comments.

I was not thinking this would be misleading because the color is still encoded in RGB, just not decimal:
hexadecimal is just a base (base 16) instead of the usual base 10 that we are used to.

10 (hexa) = 16 (decimal)
FF (hexa) = 255 (decimal)

FF 0 0 (hexa)= 255 0 0 (decimal)
the first value corresponds to Red the second to green and the third to blue in both cases. 

When I write colors I think of them in RGB space and write either hexa or decimal.
I will clarify the comment anyway
