### ISSUE TITLE
Keyboard Actions

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#264]
In light of the new stacking feature, I also tested the legacy actions.

First, they all are somewhat unintuitive due to the requirement of the mouse cursor to be inside the window. 
If possible, **focus should be enough**.

-`Pause process on Alt+Shift+Pause`
Ctrl as hotkey doesn't work, and Win+Pause is already mapped to the info screen.

-`Kill process on Ctrl+Alt+F4`
Ctrl as hotkey doesn't work, and Ctrl+Win+F4 is already mapped to "close virtual desktop".

-`Suspend/Resume AltSnap based on Scroll lock state`
No complaints.

-`Stack with Alt+Page up/down`
Ctrl+PageUp/Dw is already in common use by almost every application.

The obvious solution to most issues would be to **hardcode Alt as the sole possible hotkey**.

**Comment by RamonUnch** [comment]
Ok, now Alt is hardcoded for all shortcuts.
The kill and Pause actions apply to the foreground window but not the Stack with Alt+Page up/down because the stack is based based on the cursor position.

[AltSnap1.55test23_i386.zip](https://github.com/RamonUnch/AltSnap/files/9307709/AltSnap1.55test23_i386.zip)
[AltSnap1.55test23_x64.zip](https://github.com/RamonUnch/AltSnap/files/9307710/AltSnap1.55test23_x64.zip)

**Comment by Ichisich** [comment]
Pretty Involved.

Quick nitpick, keyboard settings don't get saved with the in-gui apply.
You first have to change something else and then commit with the window Ok/Apply.

**Comment by Ichisich** [comment]
`SnaptoSide/Corner` in its current form is pretty useless as a keyboard shortcut.
A better functionality would be `Seek Empty Space` and `Rotate through Zones`, given that the mouse can't specify the location.
