### ISSUE TITLE
Perform an action from the command line

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#285]
This is actually something that is quite simple to do.
You can Invoke AltSnap from the command line to perform an action on the focused window or at the current point location.
This is easily done with the `-a` parameter:
`AltSnap.exe -afAlwaysOnTop` Will Toggle the Always on top flag for the foreground window
`AltSnap.exe -apAlwaysOnTop` Will Toggle the Always on top flag for the pointed window.

It will only work if AltSnap is already running and if you did not enable the multiple instance mode.
This may become handy if you need to better interface AltSnap with other accessibility software like ahk, external input/controller devices etc.

[AltSnap1.57test3_i386.zip](https://github.com/RamonUnch/AltSnap/files/9423103/AltSnap1.57test3_i386.zip)
[AltSnap1.57test3_x64.zip](https://github.com/RamonUnch/AltSnap/files/9423106/AltSnap1.57test3_x64.zip)

**Comment by Ichisich** [comment]
Works great:
![grafik](https://user-images.githubusercontent.com/31080003/186625450-23258c9d-7b57-4d57-b72b-ddd6be78a3d5.png)

**Comment by grandoth** [comment]
Non-valued added comment: This reminds me of a time when I didn't know better. Almost 20 years ago now, I used Autohotkey to pickup hotkeys to trigger NirCmd command line actions which AltSnap now allows 😄 (different use case). That was instead of having Autohotkey actually move windows around which I did later. An evolution of tools eventually led me from library of shortcuts to make grids for windows and move them around to AltDrag/AltSnap and FancyZones. Thanks for your work.
