### ISSUE TITLE
[Feature Request] Action menu option to show regular contextmenu.

### ISSUE THREAD

**Issue by yontekh** [RamonUnch/AltSnap#302]
I would appreciate it, if the 'action menu' contained an option to "show normal contextmenu".
![image](https://user-images.githubusercontent.com/77578151/192003947-e696a0ad-a6ff-40a3-bfdd-c573c62fe3b4.png)

My usecase:
When I rightclick a titlebar it shows the actionmenu, this is what I want most of the time. But sometimes I need it to show the normal context menu instead, so rightclick as-if alt-drag was disabled or the process was blacklisted.
I would then have to disable alt-snap, rightclick, and re-enable it.

Thanks for reading and considering. If this is not possible or you dont want to add it I understand.

**Comment by RamonUnch** [comment]
Interesting Idea, I will see if how feasible it is.
An alternative way which is already available is to use the alternate action key:
For example you can setup Ctrl as a key for alternate action, then when you will press Ctrl+Right click in titlebar, then the normal menu will popup. This is because by default there are no alternate actions mapped for the titlebar.

**Comment by RamonUnch** [comment]
Also if you want to perform an Alt+Click inside a window without AltSnap intercepting it, you can do Alt+Long Click. This works for all mouse buttons.

**Comment by yontekh** [comment]
thanks, both those options work fine for my work PC setup, thank again!

I also use AltSnap on a MediaPC connected to a TV. The remote I use for this cant click a mouse button while holding alt or ctrl, so it would still be useful for that use case. Until then I  can just click the tray icon to quickly disable and enable AltDrag.

**Comment by RamonUnch** [comment]
With this build the **Send original click** menu entry was added. It does not apply when you performed an Alt+Click because it would clutter the menu and not be more practical than a long click.

[AltSnap1.57test23_x64.zip](https://github.com/RamonUnch/AltSnap/files/9686524/AltSnap1.57test23_x64.zip)
[AltSnap1.57test23_i386.zip](https://github.com/RamonUnch/AltSnap/files/9686525/AltSnap1.57test23_i386.zip)

**Comment by yontekh** [comment]
Yes! this is perfect, thanks a lot!
