### ISSUE TITLE
Slight Incompatability With FluentSearch

### ISSUE THREAD

**Issue by TooSpooky** [RamonUnch/AltSnap#309]
Hello,

When using altsnap in conjunction with fluentsearch, when you press alt and drag a window it opens Fluent Search which is usually activated by pressing control +alt.

Apologies if this is already easily fixable via the config.

Thanks for your time and take care!

**Comment by RamonUnch** [comment]
When at the end of an Alt+Drag, AltSnap has to send the control key, otherwise the menu would get selected.
Because of this if a program starts on Alt+Ctrl, then it will start.
You have the obvious options to change the hotkey to the WinKey for AltSnap or to change the Fluent Search's shortcut.

I think I can add an advanced option to disable sending Ctrl, but it will decrease very significant the usability of AltSnap.
So I think the better Idea will be to try if other keys can be sent to obtain the same effect, so that it can be configured as a per-user basis.

**Comment by RamonUnch** [comment]
@TooSpooky

With this build of AltSnap you can now configure the key that is sent at the end of a movement.
Set to `00` do disable key sending at end of movement. Or have a look at the [full virtual-key list ](https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) for a better choice.

```
In the [Input] section of the .ini file.

EndSendKey=11
; Key sent at the end of a movement to avoid menu selecting because of Alt
; or to avoid poping up the Windows menu when using WinKey as a hotkey.
; Since the original AltDrag the default value is 11 (VK_CONTROL).
; You can try sending other keys or set to 00 to disable key sending.
; You can try WinKey(5C) if you use Alt(12) as a hotkey or vice-versa.
; You can try using some of the undefined VK-codes such as 0E.
```

To use the build, quit AltSnap, and replace `AltSnap.exe` and `hooks.dll` with the new versions.
Then open your .ini file (middle click on the tray Icon) and add the `EndSendKey` option to the `[Input]` section with the desired value.

I would suggest you try `EndSendKey=5C` (VK_RWIN) because you use Alt as a hotkey and Alt+Win will prevent menu being selected.
I also did some *quick* tests using `EndSendKey=0E` which corresponds to an undefined key. it seems to work, but I do not know if all programs will like it... I also tried  `EndSendKey=FF` again *very quickly* and it also seems to work fine.

[AltSnap1.57test27_x64.zip](https://github.com/RamonUnch/AltSnap/files/9784310/AltSnap1.57test27_x64.zip)
[AltSnap1.57test27_i386.zip](https://github.com/RamonUnch/AltSnap/files/9784311/AltSnap1.57test27_i386.zip)

**Comment by TooSpooky** [comment]
Sweet, I'll test that out. Curious what key might be the best. 

Thanks a ton for the quick attempt to fix haha.

Take care!

**Comment by TooSpooky** [comment]
@RamonUnch I haven't tested it extensively but from some basic usage of just moving or resizing windows it seems RWIN is a good choice, haven't run into an issue yet but i'll continue testing.

**Comment by RamonUnch** [comment]
Happy to see that,
I am testing Myself `EndSendKey=0E`. The problem with RWIN is that it will work properly only if you only use `Alt` as a kotkey. So in your case I beleave this is both a safe ad reliable solution, but it cannot be set as the default value for eveybody.
Hopefully `0E` could be used on any config and become the new default. More testing will be required and Ctrl will remain the default for now.

**Comment by TooSpooky** [comment]
Huh interesting, might have to try out 0E myself. Alt seems to be a fine hotkey for me currently so probably won't right away. 

But thanks again for the quick solution! Take care!

**Comment by 6Tom** [comment]
Hi friends, 
I encountered a similar situation when using AutoHotkey. I think it is universal. It should also have an effect on Altsnap. Let me share it with you.

I think you can try `EndSendKey=FF`, which is a virtual key without mapping.

The following is quoted from the official documentation of AutoHotkey:
> Good candidates are virtual key codes which generally have no effect, such as vkE8, which Microsoft documents as "unassigned", or vkFF, which is reserved to mean "no mapping" (a key which has no function).
> 
> Note: Microsoft can assign an effect to an unassigned key code at any time. For example, vk07 was once undefined and safe to use, but since Windows 10 1909 it is reserved for opening the game bar.

So I came to the conclusion that `FF` is a good key, which I am using. It seems that it will not be assigned by Microsoft one day in the future. You can try it.
