### ISSUE TITLE
Move and snap without a hotkey

### ISSUE THREAD

**Issue by ParticleMon** [RamonUnch/AltSnap#311]
It should be possible to move and snap all windows with a left click on the title bar without a hotkey.

For instance, Windows Terminal requires the workaround of a hotkey to move and snap. Another workaround is enabling "long left-click" but this conflicts with long-click controls, such as the Chromium-based browser extension Better Back Button. And "Elevate" doesn't help.

Is "Move window" somehow different from "Move windows with a long left-click"?

Some settings:
* Mouse actions > Primary / Alternate / Title bar > Left mouse button: Move window
* "Use specific actions when clicking the Title bar": Without hotkey = enabled, With hotkey = disabled
* Activate with click > "Move windows with a long left-click" = disabled

Windows 10 Build 19044

**Comment by RamonUnch** [comment]
I do not really understand the issue here, you move and snap without hotkey by using setting titlebar action to move as suggested so where is the problem

The Move Window with a long left cick is the same nature than Alt+click, and snapping does work here too.

Windows Terminal is buggy and thus AltSnap purposefully disables the feaures on it. see issue #11 for more details.
