### ISSUE TITLE
Window rolled up will partially expand when dragging

### ISSUE THREAD

**Issue by du33169** [RamonUnch/AltSnap#321]
Operating System:  Windows 10 21H2, also reproducible on Windows 7

I select _Roll/Unroll_ window as the action of **Scroll wheel** to roll up some windows not that important.

However, when I drag on the titlebar, the window expands partially:

![expand](https://user-images.githubusercontent.com/46591250/199419841-857dbc06-3334-4686-ab4d-36a4486f7fdc.gif)

Infomation that worth mentioning:

- This occurs with a normal drag, i.e. when I press the left button and move it.
The window will keep rolled up when moving with AltDrag.
- This doesn't occur on those old, native programs, such as cmd or notepad, 
but it affects explorer, Windows Settings and most of other programs.

**Comment by RamonUnch** [comment]
There is not much I can do about this, If you move With AltSnap instead of the native drag, then you will not have this problem.

The reason this occurs is because some programs check themselves for the minimum height they want for their window? as soon as you move them via their title-bar, then they are informed to double check for their minimum height/width and resize accordingly.

**Comment by RamonUnch** [comment]
Sorry to close it but I am trying to focus on what I can actually hope to fix.
