### ISSUE TITLE
[Feature] auto update option

### ISSUE THREAD

**Issue by ctf0** [RamonUnch/AltSnap#325]
thank you so much for your hard work & support on this app.

i wanted to ask if its possible to add a couple of enahcments to the app in the shape of

1. <s>a way to quickly navigate to the ini file or at least add a shortcut for in the user documents instead of manually navigating to `C:\Users\xxx\AppData\Roaming\AltSnap` everty time u want to change something. for example `AutoHotkey` sets & load the user config from user documents.</s>

2. an option to auto update the app, or at least a button to manually update the app from the config window instead of checking github every now & then to know if something new was realeased.

**Comment by Ichisich** [comment]
1. middle-click the tray icon.

**Comment by Ichisich** [comment]
https://github.com/RamonUnch/AltSnap/wiki#configuration

In regard to updates, there is a Chocolatey package, but I'm not knowledgeable about that.
So try for yourself:
https://github.com/RamonUnch/AltSnap/wiki#installation

**Comment by ctf0** [comment]
> In regard to updates, there is a Chocolatey package, 

sadly my choco setup is a mess and i prefer to stay away from it, but if this is the way to go , we can close the ticket.

**Comment by RamonUnch** [comment]
I will add an entry in the tray menu I guess because it is quite hidden.

Also I already discussed the auto update feature.
I prefer to let the package manager handle updating rather than doing it myself this is simpler to write and less prone to attacks.

So you can use chocolatey, winget, or scoop. The chocolatey package is the official package that I maintain myself.

**Comment by ctf0** [comment]
sure np, thanks alot again for ur help and support
