### ISSUE TITLE
Pure Mouse Use: Request RMB + drag to invoke window movement or resize

### ISSUE THREAD

**Issue by colecovizion** [RamonUnch/AltSnap#340]
I love AltSnap, thank you so much!

I like using Altsnap purely on my mouse without the keyboard. I would love to see the ability to do a right-click + drag to invoke a window move or resize.

Thanks for keep this software alive!

**Comment by RamonUnch** [comment]
You can already make this behavior:
1) Open the ini file (Middle click the Tray Icon)
2) Look for Hotclicks option and set `Hotclicks=03`. save file.

Now when you right-click you will have the resize action (you can configure the resize action to move the window in the centaral region).

To generate a normal right click you need to perform a long right click.
If you do not like it, you can set the **Avoid blocking Alt+Click** option in the general tab of the ini file.

In this case right click down/up will pop up the context menu and Right clic + drag + release will resize the window.

I would advise doing this with a less important mouse button like the middle mouse button. or Xbuttons (if you have them).

**Comment by RamonUnch** [comment]
Actually for now it is not really usable because the click is blocked on blacklisted windows
I will work on improving this!

**Comment by colecovizion** [comment]
Thanks for your help and looking into this. If the right-click can work elegantly, it would be ideal since it's easier to invoke than the middle click on my mouse.

**Comment by RamonUnch** [comment]
[AltSnap1.59test1_i386.zip](https://github.com/RamonUnch/AltSnap/files/10355522/AltSnap1.59test1_i386.zip)
[AltSnap1.59test1_x64.zip](https://github.com/RamonUnch/AltSnap/files/10355523/AltSnap1.59test1_x64.zip)

Have a try with this build of AltSnap and as stated before:
Set `Hotclicks=03` in the   `[Input]` section of the .ini file.
also set `PiercingClick=1` in the `[Advanced]` section of the .ini file.

Now right click+Drag will resize and Right click without drag will popup the context menu.
The way it works is that in case no drag occurred, the right click, that was blocked by altsnap, is forwarded when you release it. If a drag occured both click down and up are blocked and the window is resized.

It works better than I expected.
You will see the cursor change to some resize arrows even if no drag occured, If you really dislike this you can set `UseCursor=3` or `0` But I would recommend to keep the default for now so that you are reminded of AntSnap interaction if something goes wrong.

You can setup the resize action so that the center resize mode Moves the window instead of resize, like this, you can move a window by Right click+drag on the central region and you can resize it by right click on the edges/corners, The size of the central region can be adjusted of course.

**Comment by colecovizion** [comment]
Wow this is so great! Having the right-click resize feels really natural to me. Plus it works if I'm on a computer that doesn't have a lot of mouse buttons to configure. 

Will this change be incorporated in 1.59 final?

Thanks again, it's a huge productivity boost for me.

**Comment by colecovizion** [comment]
Is there a way I can leave a small donation to help contribute?

**Comment by RamonUnch** [comment]
This will be included in the next release indeed.
For now there is no donation options.

**Comment by colecovizion** [comment]
Thanks very much. When there is a donation option I'll be sure to contribute. Until then, thanks for all your work on this project.
