### ISSUE TITLE
Snapping gap different between windows and screen border (seems doubled)

### ISSUE THREAD

**Issue by apotenza92** [RamonUnch/AltSnap#347]
Self-explanatory, but the snapping gap set in pixels seems to be doubled between windows compared to the gap between a window and the screen border. Screenshot, observe red line vs purple line. Snapping gap set at 24 pixels.
![image](https://user-images.githubusercontent.com/53612685/211977907-638e6322-ad2f-4c6e-bbaf-b604af3825f9.png)

**Comment by RamonUnch** [comment]
This is intended behavior, the snap gap is more of an afterthought that was originally designed to compensate for some 1pixel invisible borders, it should be renamed probably renamed because it just adds invisible borders to the window.

**Comment by marcselman** [comment]
@RamonUnch
I understand that it's intended behavior, because it's just an invisible border, but for me (and OP) it's not wanted behavior.
Is there a way to make this work?
Maybe by having invisible window borders always overlap, or by adding an extra offset to the screen edges?
It's a great feature and would be fantastic if it works as expected.
