### ISSUE TITLE
Extended FancyZones compatibility

### ISSUE THREAD

**Issue by WouterVanGoey** [RamonUnch/AltSnap#359]
### Discussed in https://github.com/RamonUnch/AltSnap/discussions/358

<div type='discussions-op-text'>

<sup>Originally posted by **WouterVanGoey** February  8, 2023</sup>
I like that the option to restore windows snapped with FancyZones was added, thanks!
Would it be possible to extend this so that I could use AltSnap to drag windows into zones?</div>

**Comment by RamonUnch** [comment]
For now AltSnap cannot read the Zones from FancyZone, so you have to setup the snap layout yourself in order to copy the current Zones. The procedure is quite simple and is described in the Wiki
https://github.com/RamonUnch/AltSnap/wiki#snap-layout-configuration

**Comment by BrokenStandards** [comment]
See %LOCALAPPDATA%\Microsoft\PowerToys\FancyZones if your interested in adding the capacity to read zones.

The applied layouts file has 2 entries per monitor, My guess without looking it up is its for the layout for horizontal/landscape and vertical/portrait orientation. The custom layouts file has all the custom ones. Match by uuid. The zones section seems to be exactly what the ini expects. So just grab it from applied layout instead of the ini and maybe add an option to output it into the ini for further customization.

**Comment by RamonUnch** [comment]
> See %LOCALAPPDATA%\Microsoft\PowerToys\FancyZones if your interested in adding the capacity to read zones.
>
>The applied layouts file has 2 entries per monitor, My guess without looking it up is its for the layout for horizontal/landscape and vertical/portrait orientation. Use it to find the uuid of the current layout. The custom layouts file has all the custom zones. Match by uuid. The zones section seems to be exactly what the ini expects. So just grab it from applied layout instead of the ini and maybe add an option to output it into the ini for further customization.

I do not use FancyZones.
This would be better off to be a separate script that converts in the FancyZones format to the AltSnap format, rather than something integrated into AltSnap.

I think FancyZones should become pointless when you use AltSnap layouts. If there is a killer feature that FancyZones has and AltSnap does not, then a new issue should be created. For example AltSnap did not support overlapped zones properly and now does. Also Editing a layout will be made easier in the next release. And now AltSnap support up to 10 layouts that will automatically be selected depending on your display.

Finally when trying to interact with specific programs like that it becomes very annoying to maintain because FancyZone can change anytime their layout format, and If a user uses any combination of AltSnap+FancyZones that is not exactly the expected one, then things will go wrong.

I added the Restore FancyZone snapped windows, because it literally takes a couple lines of code as the way AltSnap saves restore information is almost the same than what FancyZones does, so when I discovered FancyZones.

**Comment by BrokenStandards** [comment]
I see. Just suggested since the wording on everything made it sound like integration was a goal rather than feature parity/replacement. I won't say I particularly care for fancy zones myself or think there is any specific killer feature. The overlay is *nice* though unnecessary (less jaring than windows snapping and changing sizes as you drag it to the correct spot). Your test window layout editor is probably better for layout editing for overlapping center-nearest-to-cursor layouts like mine. (ultrawide with 5x2 middle priority grid, 3x2 middle priority grid, 4x2 grid, 2x2 grid, 2x2 priority left, 2x2 priority right, and Nx1 version of all)

Honestly overlays is the only thing I miss from them. And maybe an easier/more obvious way to edit the layout. I'm not entireely certain if I can do that from the gui as the wiki seems to suggest, but I managed to find directions in issues on what to do in the ini.
...

**Comment by RamonUnch** [comment]
@BrokenStandards Look at #511 for snap layout preview into AltSnap. It is still WIP, but I already close this Issue.
