### ISSUE TITLE
Make Escape Key to Unhook Configurable

### ISSUE THREAD

**Issue by jet082** [RamonUnch/AltSnap#386]
As per conversation in #380.

It would be nice to be able to set the Escape key to something else, ideally even a combination of keys, as many mobile keyboards do not have an escape key. Adding it to the "Shortcut for Action" should work I think.

**Comment by RamonUnch** [comment]
That is an easy one:
[AltSnap1.59p2_x64.zip](https://github.com/RamonUnch/AltSnap/files/10950386/AltSnap1.59p2_x64.zip)

in the `[Input]` section of the ini file:

```ini
ESCkeys=1B
; List of keys that will behave like ESCAPE, ie,
; end the movement and reset the state. default is 1B (ESCAPE)
```
If the option is not present, the usual ESC is used, you can specify several space separated keys as usual.

**Comment by RamonUnch** [comment]
This is just a key list, it does not support key combinations/shortcuts, but any key would work, because it will not interact with the system unless a movement is going on, so you could use any alphabetic keys ans still be able to use it.
In your case, I think pressing Alt+Q solves the problem independently of AltSnap.
