### ISSUE TITLE
Restored FancyZones snapped windows have incorrect size

### ISSUE THREAD

**Issue by acceptibru** [RamonUnch/AltSnap#395]
AltSnap 1.59 Powertools 0.68 3840*2160 resolution

Restoring windows snapped by FancyZones seems to reduce them by half (maybe dpi issue?...)

On the video I snap a window with fancyzones shortcut, then drag out with fancy zones restoring it correctly, then the same with altsnap restoring a tiny window instead

https://user-images.githubusercontent.com/13321381/226123162-be00e37a-fd53-4218-9b00-9475fc4335c0.mp4

**Comment by RamonUnch** [comment]
I guess you are using the **Restore FancyZone snapped windows** option.
It is somewhat expected that it stops working at some point, because FancyZone is free to change the way it stores the restore size.

Could you try the same thing but with 96dpi setting? (100% scaling)
I am not sure if this was the same with previous FancyZones. If you could confirm that, then the fix would be trivial (I just have to scale back to current DPI).

**Comment by acceptibru** [comment]
> I guess you are using the Restore FancyZone snapped windows option.

Yes

> Could you try the same thing but with 96dpi setting? (100% scaling)

Yep, works correctly on 100% scaling

**Comment by acceptibru** [comment]
Yeah, it looks like fancyzones recalculates dimensions,. When I edit the zones in fancyzones with 200% scaling it shows halved dimensions in pixels, like 1080 height instead of 2160. When the scaling is 100% then the same zones have correct pizel dimensions

**Comment by RamonUnch** [comment]
I could not test myself but this one should fix the problem.
Just quit Altsnap, and replace both AltSnap.exe and hooks.dll 
[AltSnap1.59fix4_x64.zip](https://github.com/RamonUnch/AltSnap/files/11009385/AltSnap1.59fix4_x64.zip)

**Comment by acceptibru** [comment]
> Just quit Altsnap, and replace both AltSnap.exe and hooks.dll [AltSnap1.59fix4_x64.zip](https://github.com/RamonUnch/AltSnap/files/11009385/AltSnap1.59fix4_x64.zip)

Works fine! Thank you
