### ISSUE TITLE
Modifier combo like "ctrl-alt" should not activate altsnap if "alt" is the activation key

### ISSUE THREAD

**Issue by dsjstc** [RamonUnch/AltSnap#427]
Functionality change request:

If my alternate action key is Alt, then holding a modifier combination like <shift><alt> should not be recognized as altsnap's activation modifier.  In vscode, for example, shift+alt+drag means column select, and I'd prefer not to have to blacklist vscode (or change my altsnap key!) to retain that functionality.

In my understanding, modifier combos are distinct, not additive -- eg, ctrl-delete should not be activated when hitting ctrl-alt-delete.  In the case of altsnap, I don't immediately see any use cases where one would want altsnap's alternate action activated by all five modifier combos that happen to include alt.

**Comment by RamonUnch** [comment]
All those keys have specific meanings for AltSnap do they cannot be hard-disabled or the program would loose a lot of functionality instantly.

I do not perfectly understand what your setup is because it seems you only use alt to activate AltSnap and you still say that you use Alt as an Alternate action key?

In anyway you have two solutions:
1) If you want to activate AltSnap with a single key you can set `MaxKeysNum=1` in the `[Advanced]` section of the ini file.
```ini
MaxKeysNum=1
; Maximum number of keys that can be pressed on the keyboard
; at the same time beyond which AltSnap click will no longer activate.
; It will not interupt AltSnap if it is already in the middle of an action.
; Default is 0 (unlimited).
```
In this case you will have to press **Alt first** to use AltSnap and if you press Ctrl+Alt (with Ctrl first) then AltSnap will not activate, same for any other combination.

2) The other option is to add Ctrl (`A2`)to the `KillKey` list in the `[Input]` section of the ini file:
```ini
Killkeys=09 2E A2
; Keys that will disable AltSnap when pressed down!
; Space-separated hexadecimal values.
; All keys from A-Z always disable AltSnap, so do not add them here.
; Default is TAB: 09 (for DisplayFusion's Alt+Tab).
; 2E for the DEL key (for Ctrl+Alt+DEL).
```

**Comment by RamonUnch** [comment]
@dsjstc does the above tricks with `MaxKeysNum` of `Killkeys` works for you?

**Comment by dsjstc** [comment]
Hey, thanks for the suggestions!  Sorry for my slowness, much going on in my life right now and I didn't want to answer carelessly.   I wasn't enough of a power user to know that I should be digging through the .ini file, thanks for the nudge!  

1. I misunderstood what I was doing on the config page, I do not use any Alternate action.

2. KillKeys A2 does not have the desired effect, AltSnap is still active when the <ctrl><alt> chord is held.  As an aside, it would be lovely to know where to look up these key IDs, since they don't seem to be the standard windows keycodes.

3. MaxKeysNum=1 works perfectly for my use case, thanks very much!  I still think this behaviour is going to be unexpected for most users, but I'm super appreciative to have a configuration that works for me.

**Comment by RamonUnch** [comment]
> KillKeys A2 does not have the desired effect, AltSnap is still active when the chord is held. As an aside, it would be lovely to know where to look up these key IDs, since they don't seem to be the standard windows keycodes.

The codes are the standard virtual key codes, you can find here: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

However you cannot use some special scancodes like `10` `11` or `12` that are Shift/Ctrl/Alt left **or** right, because they are translated at a higher level.

**Comment by jefflord** [comment]
@RamonUnch, once again, thanks so much for continued work on this fantastic app. It's saved my so much time and headache. No 4k monitor is complete without this.  

OK, I agree with @dsjstc here!!!


> 3\. MaxKeysNum=1 works perfectly for my use case, thanks very much!  I still think this behavior is going to be unexpected for most users, but I'm super appreciative to have a configuration that works for me.

`MaxKeysNum=1` works great but, this normal setup where just `ALT` is the activation modifier key, it seems like it should be ignored of `CTRL` is also pressed, _by default_. 

My use case is Visual Studio:
```
Hold Ctrl + Alt and click with the mouse at the desired locations to place multiple cursors anywhere in the code.
```

Me and I think @dsjstc would have expected AltSnap to understand that if I have just one, `MaxKeysNum=1` should be one already. 

If that's not an option or there are many good technical reasons why you can't know/do that, that's fine, but then updating the AltSnap Config UI would help a lot. 

Options: 
1. Expose MaxKeysNum as select with options Unlimited, 1, 2, 3 ,... (I like this option)
2. Explain this with updated text in the screen, change 
```
You can add any key by editing the ini file.
Use the shift key to snap windows to each other.
```
   to
```
You can customize keys, adjust the maximum number of simultaneous key presses, and more by editing the ini file.
```

I think the text you have "Use the shift key to snap windows to each other." should be moved to the General tab, where other snap options are mentioned. 

### Bonus Option
Finally, there might be another way to think about this.
A "simple" toggle that says, "If any non-activation key is already pressed, then activation will not happen." 

If you implemented this, at least in MY use case `Ctrl + Alt and click`, if I do them in that order Ctrl then Alt, AltSnap will not activate, and VS will do its thing correctly.

**Comment by RamonUnch** [comment]
So in short the MaxKeysNum option works fine for you but you think it should be the default?
It would be strange because AltSnap ws designe with the combine ctrl/shift combo actions for extended actions, however I agree that it should be in the UI so that it is easier for the user to enable.

**Comment by jefflord** [comment]
> So in short the MaxKeysNum option works fine for you but you think it should be the default? It would be strange because AltSnap ws designe with the combine ctrl/shift combo actions for extended actions, however I agree that it should be in the UI so that it is easier for the user to enable.

1. Yeah, that sums it up, but since @dsjstc summary fell on deaf ears I decided to elaborate. 
2. "AltDrag" seems have been just ALT, but "AltSnap" was deigned to use "ctrl/shift"? Weird?! 

In any case, the exitance of "MaxKeysNum" is weird. I don't think the setting should exists. The number of keys is the number of keys.

**Comment by dsjstc** [comment]
> No, the default for "MaxKeysNum" should not be 1. The "default" should be that if your activation key is pressed but also a non-activation key is pressed, then activation should not happen. That is what should be default.

That is a great summary.  Only the exact specified chord should activate AltSnap -- a superset of the chord should *not*.

**Comment by RamonUnch** [comment]
Optionally I agree  but by default people use Shit+Alt+double click to minimize, Ctrl+Alt+Move to clamp to a given monitor, shift+move/resize to force edge-to-edge window snapping etc.  There is a lot to default behavior for AltDrag and AltSnap that alter any action based on other keys press and I do not want to break all this power by default.

**Comment by jefflord** [comment]
> Optionally I agree but by default people use Shit+Alt+double click to minimize, Ctrl+Alt+Move to clamp to a given monitor, shift+move/resize to force edge-to-edge window snapping etc. There is a lot to default behavior for AltDrag and AltSnap that alter any action based on other keys press and I do not want to break all this power by default.

This makes sense. I know there's a lot more going on than just ALT+Click. `MaxKeysNum` should never default to `1`, ever. Also, it really should never need to be set to `1`. 

If you can make this (https://github.com/RamonUnch/AltSnap/issues/427#issuecomment-2661615924) change then I'll be able to change my back to `0`. 

Have we found and acceptable solution that will get implemented?

**Comment by RamonUnch** [comment]
I do not understand your propositio, Shift and Ctrl are not activation keys, they are modifier keys. and they have not to be configured by users, they are hard-coded since day 1

**Comment by jefflord** [comment]
OK, yeah, and we want to be able to be able to press the modify buttons before OR after activation. 

My thought (wrong) was that we could only consider the modifiers after activation. Activation means you have the JUST activation key down (usually ALT) and also use the mouse (any click or wheel). That is the point that AltSnap is activated.

After that point, if modifiers are added they do what they should do. I know this won't work because users expect to be able to press the modifiers before and during. 

I can see we are beating a dead horse. 

Sadly/happily, 
1. The `Killkeys` options works, if you add `A2`. and you like the way that behaves and the side effects. 
2. The `MaxKeysNum` works also, if you like those side effects. 

Current you can pick you poison, if you know this and don't mind discovering this via trial and error and editing the ini file. 

I cannot think if a good way to resolve this in code. 

I cannot think of a nice way to present `Killkeys` or `MaxKeysNum` in the config UI. 

I this defeat? 😒 

I hope I did not waste too much of your time on this, again.
