### ISSUE TITLE
about the always on top problem

### ISSUE THREAD

**Issue by willson83** [RamonUnch/AltSnap#442]
After setting the window of a software (such as Notepad) to be always on top, you operate another software (such as Explorer), when you no longer need the Notepad to be always on top, if the window of Notepad is not activated In the state of canceling the always on top, it is still always on the top relative to explorer, until you activate its window or switch to the window of the third software, this relative effect will be canceled. Is it possible to activate its window while canceling the always on top effect of a software? thanks.

**Comment by RamonUnch** [comment]
I think I understand the problem, once a window is foreground, it cannot get in front of a window that was topmost because Windows still thinks it is foreground so he does nothing.

A workaround (for now) is to use the **Lower window** action to disable the topmost attribute, as it will also push the window back, meaning you no longer see it.

I think you are right and that the fix should be to ensure the topmost window should get selected when you un-topmost it, so that it properly gets behind when you select another window.

Maybe it should follow the **Focus window when dragging** option? Some people might prefer to have less focusing happen. So do you use this focus while dragging option? Just to know if I should use this setting...

**Comment by willson83** [comment]
Thank yo for your reply. I don't use the focus while dragging option, so I think that is very good if it follows the Focus window when dragging option.

**Comment by RamonUnch** [comment]
Well use this build that should always focus a window you want to topmost/untopmost.

[AltSnap1.61test0707_x86_64.zip](https://github.com/RamonUnch/AltSnap/files/11980777/AltSnap1.61test0707_x86_64.zip)
[AltSnap1.61test0707_i386.zip](https://github.com/RamonUnch/AltSnap/files/11980778/AltSnap1.61test0707_i386.zip)

**Comment by willson83** [comment]
it fixes the problem. Thank you for the update.
