### ISSUE TITLE
Non-resizable Window Snapping

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#447]
Currently, non-resizable applications that get snapped also get resized.
A more intuitive handling would be to just move non-resizable windows to the next edge instead, identical to the `Move to next Edge` action.
The approach could be dependent on the `Resize all windows` option.

**Comment by RamonUnch** [comment]
For now when you disable the **Resize all windows** option, non-resizable windows are not snapped/resized in any way. So in this case it could be a good idea to transform the snapping into a a move to next edge instead as you say, I am not sure i would be so great however because it mean the action would depend on the type of window which might be unintuitive. However in this case it would make sense because the snap to next edge is kind of similar to snapping but without resizing the window.

**Comment by Ichisich** [comment]
> For now when you disable the **Resize all windows** option, non-resizable windows are not snapped/resized in any way.

Maybe it's different on older Windows Iterations, but in Windows 10 a non-resizable window gets snapped and resized.

![1](https://github.com/RamonUnch/AltSnap/assets/31080003/bc2bbbb2-2069-4e04-aaef-22b9cbb05d0e)

Snapped to the top right corner:
![2](https://github.com/RamonUnch/AltSnap/assets/31080003/42a69061-2758-4076-817d-ed3e2013a1fa)

**Comment by RamonUnch** [comment]
You are right, when using the `Snap to monitor side/corner` action directly or via the menu, it still gets snapped. 
If you use the double-right-click or if you drag to the screen corner it, snapping should be disables though, 
Unless you set the `AResize` blacklist to `*|*` or something.

I will first fix that and then see how it can be improved.
