### ISSUE TITLE
Home key sends the Control key only with AltSnap is running

### ISSUE THREAD

**Issue by AstudilloMarillo** [RamonUnch/AltSnap#500]
I don't know why, but for some reason when AltSnap is running, clicking the Home key sends the Control key. This is only when I have the 'Action without click' enabled in the Keyboard section of the configuration menu. I don't believe I have the Home key configured for anything in AltSnap so really not sure why this happens.

I attached my .ini to troubleshoot.
[AltSnap.zip](https://github.com/RamonUnch/AltSnap/files/13678578/AltSnap.zip).

Edit: to be clear, the Home key sends Control+Home, not just Control.

**Comment by RamonUnch** [comment]
Well it seems in your ini file you use the Home key as a hot key:
```
Hotkeys=A6 05 06 24
```
Also 05 and 06 should do nothing because mouse buttons are configured in the `Hotclicks` list.

24 is the home key.

Then when a movement ends, AltSnap will send the key configured by `EndSendKey` this is to avoid menu getting selected.
in your case you have the default:
```
EndSendKey=11
```

You can also try another value like FF if you still want to use home as a hotkey, but I would not recommend to use home as a htkey.

**Comment by RamonUnch** [comment]
EDIT: `EndSendKey=11` `11` means Control key.

**Comment by AstudilloMarillo** [comment]
Oh, that's riiight, a while back I was trying to figure out how to set Mouse Button 4 as a 'hotkey' before I managed to understand how that worked. Not sure why I was also trying 24, but maybe I was just messing around to see how the hotkey system worked. Forgot to check that list, I just did a ctrl+f search on 'home' in the .ini file lol. Thanks, this was driving me mad, haha.
