### ISSUE TITLE
Add feature to cancel the default action of modifier key after timeout

### ISSUE THREAD

**Issue by viocha** [RamonUnch/AltSnap#501]
![image](https://github.com/RamonUnch/AltSnap/assets/66580331/1ead65bb-a0ff-4e64-a288-2d40e4046b2f)

**Comment by RamonUnch** [comment]
I am not sure what you are asking for and what you are trying to achieve.

It depends on what action is configured for MB4. If you set Nothing, then clicking MB4 will be forwarded if no action is done. If you set Move or Resize, then, if you click for more than a double click delay (~400ms by default). then the click will be forwarded on release.

If you setup any other action for MB4 then The action is instantly performed on MB4 and there is no possibility to cancel the action because it is done as soon as MB4 is pressed.

**Comment by viocha** [comment]
Thank you, I understand
