### ISSUE TITLE
Low framerate when dragging/resizing.

### ISSUE THREAD

**Issue by astro75** [RamonUnch/AltSnap#87]
It feels really choppy to drag the window using Alt+Drag when compared to regular dragging on the top window bar.
This effect is even more exaggerated on a 120Hz monitor.

**Comment by mikkorantalainen** [comment]
I think it would be better if RefreshRate actually set sleep in ms but had implementation defined minimum value. The code currently runs `RefreshRate+5` which means that when you set RefreshRate to 2 you actually get 7 and when you set it to 15 (to slightly undershoot 60 Hz display to avoid missing any frames) you actually get 20 ms and get overshoot for every frame.

Maybe sleeping for `max(RefreshRate, 5)` instead?

**Comment by mikkorantalainen** [comment]
And unless there's some OS specific limitation, min value should be probably 4 because 240 Hz displays have 1000 ms / 240 = 4.16666... frametime and having 4 ms sleep there would probably be okay.

**Comment by RamonUnch** [comment]
> The code currently runs RefreshRate+5

Actually no, you misread the code, this 5 extra ms ONLY occurs at the end of a movement (when you release the mouse) to avoid bugs with Chromium based apps.
If you are using Windows 8/10 then, because desktop composition is enforced, even a Sleep(0) will force a wait for an extra vsync because Windows ensures other threads are executed a little before returning even from Sleep(0).
When you set RefreshRate=0, AltSnap does not even Call the Sleep function UNLESS you released the mouse cursor.
https://github.com/RamonUnch/AltSnap/blob/3b54b5ad5a6e8fd6c7c92983d7717f65c8749a9c/hooks.c#L960-L975
