### ISSUE TITLE
W11 Snap

### ISSUE THREAD

**Issue by xzayn** [RamonUnch/AltSnap#89]
The new Windows11 can show snap options when the head is pushed to the edges. Can AltDrag do it?

**Comment by RamonUnch** [comment]
I do not exactly know this feature, I have no way to use Windows 11 for now and probably not anytime soon.
Integration with newer snapping is planned though see issue https://github.com/RamonUnch/AltDrag/issues/80.
For now there is no snapping layout implemented other than the sides/corners aero-style snapping. (with smart aero-snapping support)

**Comment by xzayn** [comment]
If you want a video I'll send one... Do you have discord?

**Comment by RamonUnch** [comment]
@xzayn 
Check the WIP issue https://github.com/RamonUnch/AltSnap/issues/97 for snap layout support.
I close this one because discussion should go to the other one. 
It should integrate with FancyZone and W11 snap layouts.
keep in mind that the first step is to use the test windows in order to create the snap layout for AltSnap, I advise to use the same layout that you use for Win11 or with FancyZones
