### ISSUE TITLE
Using Ctrl or Shift as well

### ISSUE THREAD

**Issue by xzayn** [RamonUnch/AltSnap#91]
I've exhausted AltDrag's two mouse buttons but ofc that's not even 10% of the functionality this utility has to offer, so can I configure extra hotkeys with Ctrl or Shift? I don't recall many apps using Ctrl or Shift+right/left clicks...

**Comment by RamonUnch** [comment]
For now you can launch several instances of AltDrag with different settings. To do this, you need to duplicate AltDrag's directory and set the config for each different version (andbe sure to check the "Allow multiples instances of altdrag")
So you could set an instance with a first hotkey for movement 
Then another instance with another hotkey for other actions.
This will definitely be improved in the future.

Also keep in mind that there are already double click with resize and move that have various actions depending also on the shift /control modifiers. 
You also have the Action menu that can be used to have all "special" actions together. Keep in mind that even though accelerators keys are hidden you can still hit a single letter to activate the corresponding action:
Ie: Alt+Click (menu opens), then hit `T` to activate always on top, `B` for borderless etc.
see: https://github.com/RamonUnch/AltDrag/wiki#accelerators-are-invisible-in-the-action-menu for more details

**Comment by RamonUnch** [comment]
Also keep in mind that Ctrl+Click and Shift + Click are used under the windows explorer for file selection. it is also used for text selection in many programs such as notepad and office.
To set an hotkey that is not Alt Win or Ctrl edit the ini file directly.

I found that the least interacting hotkey is the WinKey, and Alt is pretty OK too.

**Comment by RamonUnch** [comment]
Also if you want several instances of AltDrag consider using this beta version in issue https://github.com/RamonUnch/AltDrag/issues/88 that has the advantage that snapping/restore information are shared between different instances of AltDrag.

**Comment by xzayn** [comment]
umm do you have discord tho?

**Comment by RamonUnch** [comment]
Nop, I do not have discord, If you want to send me a video, you can link it in the issue maybe.
Otherwise your suggestions and comments are taken into account (like for everyone) and I will work more on it when I get more time outside of my job.

**Comment by RamonUnch** [comment]
With this beta version you can manually edit the .ini file and set in the `[Input]` section of the `.ini`

```
LMBB=Resize
MMBB=Maximize
RMBB=Resize
MB4B=Nothing
MB5B=Nothing
ScrollB=Volume
HScrollB=Nothing
```
This are alternate actions (with a `B` sufix) that replaces the default actions (without the `B` sufix) you set on the GUI.
You also need to setup which key is used as a modifier key (look at the Hotkeys section of the [Keyboard] tab in the config dialog.

For example you can set Alt and Win as hotkeys then set Win as the modifier key, then Alt+any click will correspond to the normal actions and Win+any click will use the `B` suffixed actions instead.

This is an improvement upon the simple Move <-> resize toggle key that I had added in order to have a single click config.
